# Generated by Django 3.2 on 2021-05-14 16:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_book_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
